#!/usr/bin/env bash
source etkilesim

postmergeBaslik="$urtotm_dialogBaslik - post-merge"

islemSurdurulemiyor="işlem sürdürülemiyor"
if ! command -v girdiAl >& /dev/null; then
    echo -e "$postmergeBaslik\n'etkilesim' betiği '$PATH' yollarında bulunamadığından $islemSurdurulemiyor."
    exit 1
fi
if ! command -v goruntu >& /dev/null; then
    mesajGoster hata "$postmergeBaslik" "'goruntu' betiği '$PATH' yollarında bulunamadığından $islemSurdurulemiyor." &
    exit 1
fi
if ! git status; then
    mesajGoster hata "$postmergeBaslik" "$PWD dizini bir git reposu olmadığından $islemSurdurulemiyor." &
    exit 1
fi

seciliDal=$(git branch --show-current)
echo "$seciliDal" dalı seçili.
if [[ $seciliDal == "main" ]] || [[ $seciliDal == "master" ]]; then
    temp=$((mktemp) 2>/dev/null) || temp=/tmp/temp$$
    trap "rm -f $temp" 0 $SIG_NONE $SIG_HUP $SIG_INT $SIG_QUIT $SIG_TERM

    if ! surumal "$temp"; then
        mesajGoster hata "$postmergeBaslik" "Yeni sürüm bilgilerini alma işlemi sırasında bir hata olduğundan $islemSurdurulemiyor." &
        exit 1
    fi
    girdi=$(head -1 "$temp") # surumal girdileri [sürüm],[sürüm mesajı] biçiminde verir
    surum=$(echo $girdi | awk -F, '{print $1}')
    mesaj=$(echo $girdi | awk -F, '{print $2}')
    # Üretim dalını yeni sürüm verisi ile tagla
    git tag -a "$surum" -m "$mesaj"
    # Sürüm görüntüsü al
    goruntu "$(basename -- "$0")"
    # Yeniden source edilmezse, 'projeGoruntuArsivi' görünür olmaz
    source "$urtotm_projeUrtotmenv"

    # MPLABX ürün yayınlamasını yap
    yayinla "$surum"
fi
