#!/bin/bash
#
# Kancalar için birim testi
# 
# Çevre değişkenleri
export urtotm_projeUrtotmDizini=/disk/Projeler/UretimOtomasyonu/Bash/UretimOtomasyonu/mplabx/test/.urtotm
PATH+=:/disk/Projeler/UretimOtomasyonu/Bash/UretimOtomasyonu/araclar
PATH+=:/disk/Projeler/UretimOtomasyonu/Bash/UretimOtomasyonu/mplabx
PATH+=:/disk/Projeler/UretimOtomasyonu/Bash/UretimOtomasyonu/mplabx/git-hooks
urtotm_projeUrtotmEnv="${urtotm_projeUrtotmDizini}/urtotm_projeUrtotmEnv"
urtotm_projeAdi="Test-MPLABX-Proje"
# Yoksa, urtotm_projeUrtotmEnv yapılandırma dosyasını oluştur
cat <<- SON > "$urtotm_projeUrtotmEnv"
export PATH+=$PATH
export urtotm_calismaDizini=/disk/Projeler/UretimOtomasyonu/Bash/UretimOtomasyonu/mplabx/test
export urtotm_projeDizini=/disk/Projeler/UretimOtomasyonu/Bash/UretimOtomasyonu/mplabx/test/mplab-proje.X
export urtotm_yedekDizini=/disk/Projeler/UretimOtomasyonu/Bash/UretimOtomasyonu/mplabx/test/yedekler
export urtotm_projeAdi=MPLAB-Proje
export urtotm_dialogBaslik="$urtotm_projeAdi - Üretim Otomasyonu"
export urtotm_projeUrtotmEnv=$urtotm_projeUrtotmEnv
SON

source "$urtotm_projeUrtotmEnv"
# pre-commit # ok - 2023-12-06 17:24
# echo "pre-commit çıkış kodu: $?"
# 
# post-commit # ok - 2023-12-06 17:24

# post-merge git komutları çalıştırdığı için proje dizininden çalıştırılmalı
pushd "$urtotm_projeDizini" >& /dev/null
post-merge # ok - 2023-12-06 17:24
popd >& /dev/null
